---
  # Dispatches an event to trigger an update of Go modules for the Bloblang playground
  name: update-blobl-playground-modules
  on:
    push:
      tags:
        - '*'
  permissions:
    id-token: write
    contents: read
  jobs:
    dispatch:
      runs-on: ubuntu-latest
      steps:
        - uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: ${{ vars.RP_AWS_CRED_REGION }}
            role-to-assume: arn:aws:iam::${{ secrets.RP_AWS_CRED_ACCOUNT_ID }}:role/${{ vars.RP_AWS_CRED_BASE_ROLE_NAME }}${{ github.event.repository.name }}
        - uses: aws-actions/aws-secretsmanager-get-secrets@v2
          with:
            secret-ids: |
              ,sdlc/prod/github/actions_bot_token
            parse-json-secrets: true
        - uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ env.ACTIONS_BOT_TOKEN }}
            repository: redpanda-data/docs-ui
            event-type: update-go-mod